"""Audit report generation — markdown and JSON."""

from __future__ import annotations

import json
from datetime import datetime, timezone

from task_audit.models import AuditReport, CheckStatus, Verdict


def format_markdown(report: AuditReport) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts = report.counts
    lines = [
        f"# Task Quality Audit: `{report.task_name}`",
        "",
        f"**Generated:** {now}  ",
        f"**Task path:** `{report.task_dir}`  ",
        f"**Layout:** {'milestone' if report.is_milestone else 'regular'}  ",
        f"**Verdict:** **{report.verdict.value}**",
        "",
        "---",
        "",
        "## 1. Executive Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| PASS | {counts[CheckStatus.PASS.value]} |",
        f"| FAIL | {counts[CheckStatus.FAIL.value]} |",
        f"| NOT APPLICABLE | {counts[CheckStatus.NOT_APPLICABLE.value]} |",
        f"| CANNOT DETERMINE | {counts[CheckStatus.CANNOT_DETERMINE.value]} |",
        "",
        f"**Validator:** {len(report.validator_errors)} error(s), {len(report.validator_warnings)} warning(s)",
        "",
        "---",
        "",
        "## 2. Detailed Checklist Report",
        "",
        "| # | Status | Kind | Description | Explanation | Evidence |",
        "|---|--------|------|-------------|-------------|----------|",
    ]

    for r in report.results:
        lines.append(
            f"| {r.item_id} | {r.status.value} | {r.kind.value} | {r.label} | {r.explanation} | {r.evidence_str()} |"
        )

    lines.extend(["", "---", "", "## 3. Critical Issues", ""])
    critical = report.critical_issues()
    if critical:
        for r in critical:
            sug = f" **Fix:** {r.suggestion}" if r.suggestion else ""
            lines.append(f"- **#{r.item_id}** — {r.explanation} ({r.evidence_str()}){sug}")
    else:
        lines.append("_No blocking critical issues detected._")

    lines.extend(["", "---", "", "## 4. Warnings", ""])
    warnings = report.warnings()
    if warnings:
        for r in warnings:
            lines.append(f"- **#{r.item_id}** [{r.kind.value}] — {r.explanation}")
    else:
        lines.append("_No non-blocking warnings._")

    lines.extend(["", "---", "", "## 5. Suggestions", ""])
    suggestions = [r for r in report.results if r.suggestion]
    if suggestions:
        for r in suggestions:
            lines.append(f"- **#{r.item_id}** — {r.suggestion}")
    else:
        lines.append("_No specific fix suggestions._")

    lines.extend(["", "---", "", "## 6. Items Requiring Manual Review", ""])
    manual = [r for r in report.cannot_determine()]
    if manual:
        for r in manual:
            lines.append(f"- **#{r.item_id}** — {r.explanation}")
    else:
        lines.append("_All non-N/A items were evaluated automatically._")

    if report.validator_errors:
        lines.extend(["", "---", "", "## 7. validate_task.py Errors", "", "```"])
        lines.extend(report.validator_errors[:20])
        lines.extend(["```"])

    lines.extend([
        "",
        "---",
        "",
        "_Generated by `./scripts/terminus audit` (read-only). See `docs/guidelines/task-auditor.md`._",
    ])
    return "\n".join(lines)


def format_json(report: AuditReport) -> str:
    payload = {
        "task_dir": report.task_dir,
        "task_name": report.task_name,
        "is_milestone": report.is_milestone,
        "verdict": report.verdict.value,
        "counts": report.counts,
        "validator_errors": report.validator_errors,
        "validator_warnings": report.validator_warnings,
        "critical_issues": [
            {"id": r.item_id, "label": r.label, "explanation": r.explanation, "evidence": r.evidence_str()}
            for r in report.critical_issues()
        ],
        "results": [
            {
                "id": r.item_id,
                "section": r.section,
                "label": r.label,
                "status": r.status.value,
                "kind": r.kind.value,
                "blocking": r.blocking,
                "explanation": r.explanation,
                "evidence": [e.format() for e in r.evidence],
                "suggestion": r.suggestion,
            }
            for r in report.results
        ],
    }
    return json.dumps(payload, indent=2)


def portal_check_uncheck(report: AuditReport) -> tuple[list[int], list[int]]:
    """Map audit results to portal CHECK/UNCHECK lists."""
    check = [r.item_id for r in report.results if r.status == CheckStatus.PASS]
    uncheck = [
        r.item_id for r in report.results
        if r.status in (CheckStatus.FAIL, CheckStatus.CANNOT_DETERMINE, CheckStatus.NOT_APPLICABLE)
    ]
    return sorted(check), sorted(uncheck)
