[package]
name = "ballctl"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ballctl"
path = "src/main.rs"

[dependencies]
ballcore = { path = "../ballcore" }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
