"""Tests for accaudit-wren: validates /app/audit_report.json produced by /app/audit.wren.

The bundled-fixture tests grade the report for /app/transactions.tsv. The toolchain
tests confirm the report is produced by running the required Wren program. The final
perturbation test re-runs /app/audit.wren on held-out generated schedules and
deep-compares to an independent reference, so a report hardcoded to the bundled
fixture (or a checker that skips the interest computation) cannot pass.
"""

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
import reference  # noqa: E402
import gen  # noqa: E402

REPORT = Path("/app/audit_report.json")
WREN_SCRIPT = Path("/app/audit.wren")
SCHEDULE = Path("/app/transactions.tsv")


def load_report():
    """Load and parse /app/audit_report.json."""
    assert REPORT.exists(), f"{REPORT} not found — did wren_cli /app/audit.wren run?"
    with open(REPORT) as f:
        data = json.load(f)
    assert isinstance(data, list), "audit_report.json must be a JSON array"
    return data


def errors_with(report, *, error_code=None, txn_id=None, account_id=None):
    """Return all error records matching the given filters."""
    result = report
    if error_code is not None:
        result = [e for e in result if e.get("error_code") == error_code]
    if txn_id is not None:
        result = [e for e in result if e.get("txn_id") == txn_id]
    if account_id is not None:
        result = [e for e in result if e.get("account_id") == account_id]
    return result


def run_wren_fresh():
    """Run `wren_cli /app/audit.wren` and return the report it produces.

    Accepts both a script that prints the JSON array to stdout and one that writes
    /app/audit_report.json directly.
    """
    exe = shutil.which("wren_cli")
    assert exe is not None, "wren_cli must be available on PATH in the image"
    proc = subprocess.run([exe, str(WREN_SCRIPT)], capture_output=True, text=True, cwd="/app")
    assert proc.returncode == 0, f"`wren_cli /app/audit.wren` exited {proc.returncode}: {proc.stderr}"
    out = proc.stdout.strip()
    if out:
        try:
            data = json.loads(out)
            if isinstance(data, list):
                return data
        except json.JSONDecodeError:
            pass
    return load_report()


# ── toolchain enforcement (report must come from running the Wren program) ────

def test_audit_wren_script_exists():
    """Verify the agent created a non-empty Wren script at /app/audit.wren."""
    assert WREN_SCRIPT.exists(), "/app/audit.wren not found — the audit must be written in Wren"
    assert WREN_SCRIPT.stat().st_size > 0, "/app/audit.wren is empty"


def test_report_is_produced_by_wren_cli():
    """Verify /app/audit_report.json equals the output of `wren_cli /app/audit.wren`."""
    committed = load_report()
    produced = run_wren_fresh()
    assert produced == committed, (
        "running `wren_cli /app/audit.wren` did not reproduce /app/audit_report.json — "
        "the report must be generated by the Wren script")


# ── schema ────────────────────────────────────────────────────────────────────

def test_report_is_json_array():
    """Verify audit_report.json exists and is a non-empty JSON array."""
    assert len(load_report()) > 0


def test_each_record_has_required_keys():
    """Verify every error record has txn_id, account_id, error_code, and a non-empty detail.

    The detail wording itself is free-form (the spec only requires "a short
    human-readable description"); only its presence as a non-empty string is checked.
    """
    for rec in load_report():
        for key in ("txn_id", "account_id", "error_code", "detail"):
            assert key in rec, f"missing {key} in {rec}"
        assert isinstance(rec["detail"], str) and rec["detail"], f"detail must be a non-empty string in {rec}"


def test_error_codes_are_known():
    """Verify only recognised error codes appear in the report."""
    known = {"MISSING_FIELD", "BAD_TXN_ID", "BAD_ACCT_ID", "BAD_DATE", "BAD_AMOUNT",
             "BAD_TYPE", "BAD_CURRENCY", "DUPLICATE_TXN", "FEE_OVERCAP", "OVERDRAFT",
             "HIGH_VELOCITY", "BAD_INTEREST"}
    for rec in load_report():
        assert rec["error_code"] in known, f"unknown error code {rec['error_code']}"


# ── field-format rules ────────────────────────────────────────────────────────

def test_missing_field_flagged():
    """Verify MISSING_FIELD is emitted for the 3-field row T000000030."""
    assert len(errors_with(load_report(), error_code="MISSING_FIELD", txn_id="T000000030")) == 1


def test_missing_field_count():
    """Verify exactly one MISSING_FIELD error is produced."""
    assert len(errors_with(load_report(), error_code="MISSING_FIELD")) == 1


def test_bad_txn_id_flagged():
    """Verify BAD_TXN_ID is emitted for T00000031 (only 5 digits after T)."""
    assert len(errors_with(load_report(), error_code="BAD_TXN_ID", txn_id="T00000031")) == 1


def test_bad_txn_id_count():
    """Verify exactly one BAD_TXN_ID error is produced."""
    assert len(errors_with(load_report(), error_code="BAD_TXN_ID")) == 1


def test_bad_acct_id_flagged():
    """Verify BAD_ACCT_ID is emitted for the AC0001 record (txn T000000032)."""
    assert len(errors_with(load_report(), error_code="BAD_ACCT_ID", txn_id="T000000032")) == 1


def test_bad_acct_id_count():
    """Verify exactly one BAD_ACCT_ID error is produced."""
    assert len(errors_with(load_report(), error_code="BAD_ACCT_ID")) == 1


def test_bad_date_future_month_flagged():
    """Verify BAD_DATE is emitted for date 20261301 (month 13)."""
    assert len(errors_with(load_report(), error_code="BAD_DATE", txn_id="T000000033")) == 1


def test_bad_date_zero_month_flagged():
    """Verify BAD_DATE is emitted for date 20260000 (month 0)."""
    assert len(errors_with(load_report(), error_code="BAD_DATE", txn_id="T000000038")) == 1


def test_bad_date_future_after_cutoff_flagged():
    """Verify BAD_DATE for T000000090, a valid calendar date (20260614) past the cutoff."""
    assert len(errors_with(load_report(), error_code="BAD_DATE", txn_id="T000000090")) == 1


def test_cutoff_date_inclusive_not_flagged():
    """Verify T000000091, dated exactly 20260613 (the cutoff), is NOT flagged BAD_DATE."""
    assert errors_with(load_report(), txn_id="T000000091", error_code="BAD_DATE") == []


def test_bad_date_count():
    """Verify exactly three BAD_DATE errors are produced (month 13, month 0, future date)."""
    assert len(errors_with(load_report(), error_code="BAD_DATE")) == 3


def test_bad_amount_flagged():
    """Verify BAD_AMOUNT is emitted for amount -10.00 (negative)."""
    assert len(errors_with(load_report(), error_code="BAD_AMOUNT", txn_id="T000000034")) == 1


def test_bad_amount_count():
    """Verify exactly one BAD_AMOUNT error is produced."""
    assert len(errors_with(load_report(), error_code="BAD_AMOUNT")) == 1


def test_bad_type_flagged():
    """Verify BAD_TYPE is emitted for type WIRE (not in valid set)."""
    assert len(errors_with(load_report(), error_code="BAD_TYPE", txn_id="T000000035")) == 1


def test_bad_type_count():
    """Verify exactly one BAD_TYPE error is produced."""
    assert len(errors_with(load_report(), error_code="BAD_TYPE")) == 1


def test_bad_currency_flagged():
    """Verify BAD_CURRENCY is emitted for currency CNY (not in valid set)."""
    assert len(errors_with(load_report(), error_code="BAD_CURRENCY", txn_id="T000000036")) == 1


def test_bad_currency_count():
    """Verify exactly one BAD_CURRENCY error is produced."""
    assert len(errors_with(load_report(), error_code="BAD_CURRENCY")) == 1


# ── simple business rules ─────────────────────────────────────────────────────

def test_duplicate_txn_flagged():
    """Verify DUPLICATE_TXN is emitted for the second occurrence of T000000001."""
    assert len(errors_with(load_report(), error_code="DUPLICATE_TXN", txn_id="T000000001")) == 1


def test_duplicate_txn_count():
    """Verify exactly one DUPLICATE_TXN error is produced (first occurrence never flagged)."""
    assert len(errors_with(load_report(), error_code="DUPLICATE_TXN")) == 1


def test_fee_overcap_flagged():
    """Verify FEE_OVERCAP is emitted for T000000037 (FEE of 30.00 > 25.00)."""
    assert len(errors_with(load_report(), error_code="FEE_OVERCAP", txn_id="T000000037")) == 1


def test_fee_overcap_count():
    """Verify exactly one FEE_OVERCAP error is produced."""
    assert len(errors_with(load_report(), error_code="FEE_OVERCAP")) == 1


# ── balance / velocity ────────────────────────────────────────────────────────

def test_overdraft_flagged():
    """Verify OVERDRAFT for T000000011 (AC000002 debits 150 against a 100 balance)."""
    assert len(errors_with(load_report(), error_code="OVERDRAFT", txn_id="T000000011",
                           account_id="AC000002")) == 1


def test_overdraft_count():
    """Verify exactly one OVERDRAFT error is produced."""
    assert len(errors_with(load_report(), error_code="OVERDRAFT")) == 1


def test_high_velocity_all_six_flagged():
    """Verify all 6 DEBITs on 20260603 for AC000003 are flagged HIGH_VELOCITY."""
    hv = errors_with(load_report(), error_code="HIGH_VELOCITY", account_id="AC000003")
    assert {e["txn_id"] for e in hv} == {
        "T000000021", "T000000022", "T000000023",
        "T000000024", "T000000025", "T000000026"}


def test_high_velocity_count():
    """Verify exactly 6 HIGH_VELOCITY errors are produced."""
    assert len(errors_with(load_report(), error_code="HIGH_VELOCITY")) == 6


# ── interest accrual reconciliation ───────────────────────────────────────────

def test_bad_interest_flagged_for_wrong_posting():
    """Verify BAD_INTEREST for T000000071 (AC000007 posts 1.00 vs a much larger accrual)."""
    assert len(errors_with(load_report(), error_code="BAD_INTEREST", txn_id="T000000071")) == 1


def test_bad_interest_count():
    """Verify exactly one BAD_INTEREST error is produced for the bundled fixture."""
    assert len(errors_with(load_report(), error_code="BAD_INTEREST")) == 1


def test_correct_interest_not_flagged():
    """Verify a correctly-posted INTEREST record (T000000002) is NOT flagged.

    The posted 9.90 equals the per-day, half-up accrual; a checker that rounds once
    over the whole period (summing then rounding) computes a different total and
    would wrongly flag it.
    """
    assert errors_with(load_report(), error_code="BAD_INTEREST", txn_id="T000000002") == []


def test_leap_year_interest_not_flagged():
    """Verify the leap-and-rate-spanning INTEREST T000000081 (AC000008) is NOT flagged.

    Its accrual (posted 62.37) crosses 2024 (366-day year, USD rate 1000) and 2025
    (365-day year, USD rate 1200); a checker that uses a flat 365-day year or a flat
    USD rate computes a different total and would wrongly flag it.
    """
    assert errors_with(load_report(), error_code="BAD_INTEREST", txn_id="T000000081") == []


def test_interest_reset_between_postings_not_flagged():
    """Verify AC000009's two consecutive correct INTEREST postings are both clean.

    A checker that fails to reset the accrual after the first posting would over-count
    the second and flag it.
    """
    assert errors_with(load_report(), error_code="BAD_INTEREST", account_id="AC000009") == []


# ── totals, ordering, clean accounts ──────────────────────────────────────────

def test_total_error_count():
    """Verify the total number of errors is exactly 19."""
    report = load_report()
    assert len(report) == 19, f"expected 19 errors, got {len(report)}"


def test_output_sorted_by_account_id():
    """Verify records are sorted by account_id ascending."""
    acct_ids = [e["account_id"] for e in load_report()]
    assert acct_ids == sorted(acct_ids)


def test_output_sorted_by_error_code_within_account():
    """Verify records within the same account are sorted by error_code ascending."""
    report = load_report()
    for acct in {e["account_id"] for e in report}:
        codes = [e["error_code"] for e in report if e["account_id"] == acct]
        assert codes == sorted(codes), f"error_codes not sorted for account {acct}"


def test_output_sorted_by_txn_id_within_error_code():
    """Verify records with the same account_id and error_code are sorted by txn_id."""
    report = load_report()
    seen = {}
    for e in report:
        seen.setdefault((e["account_id"], e["error_code"]), []).append(e["txn_id"])
    for key, ids in seen.items():
        assert ids == sorted(ids), f"txn_ids not sorted for {key}"


def test_clean_account_ac000005_has_no_errors():
    """Verify fully clean account AC000005 does not appear in the report."""
    assert errors_with(load_report(), account_id="AC000005") == []


def test_full_report_matches_reference_on_bundled_fixture():
    """Verify the report matches the independent reference for the bundled schedule.

    Compared on the structural fields (account_id, error_code, txn_id) and their
    order; the free-form `detail` wording is not asserted.
    """
    report = load_report()
    ref = reference.audit(SCHEDULE.read_text())
    assert reference.normalize(report) == reference.normalize(ref)


# ── held-out perturbation / anti-hardcoding (runs last) ───────────────────────

def test_zzz_perturbation_on_generated_holdouts():
    """Re-run /app/audit.wren on generated held-out schedules; deep-compare to reference.

    A report hardcoded to the bundled fixture, or a checker that skips the interest
    accrual, diverges on these inputs. Restores the bundled schedule/report afterward.
    """
    assert WREN_SCRIPT.exists(), "/app/audit.wren not found"
    exe = shutil.which("wren_cli")
    assert exe is not None, "wren_cli must be on PATH"
    backup_schedule = SCHEDULE.read_text()
    backup_report = REPORT.read_text() if REPORT.exists() else None
    seeds = [1, 7, 13, 42, 99, 123, 777, 2024, 31337, 65535]
    seen_norm = []
    try:
        for seed in seeds:
            text = gen.generate(seed)
            SCHEDULE.write_text(text)
            if REPORT.exists():
                REPORT.unlink()
            proc = subprocess.run([exe, str(WREN_SCRIPT)], capture_output=True, text=True, cwd="/app")
            produced = None
            out = proc.stdout.strip()
            if out:
                try:
                    produced = json.loads(out)
                except json.JSONDecodeError:
                    produced = None
            if produced is None:
                assert REPORT.exists(), f"held-out seed {seed}: /app/audit.wren produced no report"
                with open(REPORT) as f:
                    produced = json.load(f)
            expected = reference.audit(text)
            assert reference.normalize(produced) == reference.normalize(expected), (
                f"held-out seed {seed}: report does not match reference\n"
                f"agent={json.dumps(reference.normalize(produced))}\n"
                f"ref={json.dumps(reference.normalize(expected))}")
            seen_norm.append(json.dumps(reference.normalize(produced), sort_keys=True))
        assert len(set(seen_norm)) > 1, "report identical across different inputs — appears hardcoded"
    finally:
        SCHEDULE.write_text(backup_schedule)
        if backup_report is not None:
            REPORT.write_text(backup_report)
