# frozen_string_literal: true

module Variform
  module Validation
    module MethodAllowlist
      ALLOWED = %w[
        adaptive_blur
        adaptive_resize
        adaptive_sharpen
        annotate
        antialias
        append
        apply
        auto_gamma
        auto_level
        auto_orient
        background
        blue_shift
        blur
        border
        bordercolor
        brightness_contrast
        charcoal
        chop
        clamp
        clip
        colors
        colorspace
        combine
        compress
        contrast
        crop
        cycle
        deskew
        despeckle
        distort
        dither
        edge
        emboss
        encoding
        enhance
        equalize
        extent
        extract
        flatten
        flip
        flop
        font
        format
        frame
        fuzz
        gamma
        gaussian_blur
        geometry
        gravity
        grayscale
        identify
        implode
        interline_spacing
        interpolate
        interword_spacing
        kerning
        label
        level
        limit
        liquid_rescale
        loader
        magnify
        median
        minify
        modulate
        monochrome
        morphology
        negate
        noise
        normalize
        opaque
        ordered_dither
        orient
        page
        paint
        pointsize
        polaroid
        posterize
        quality
        quantize
        radial_blur
        raise
        recolor
        reduce_noise
        repage
        resample
        resize
        resize_to_fill
        resize_to_fit
        resize_to_limit
        rotate
        sample
        sampling_factor
        saver
        scale
        screen
        sepia_tone
        shade
        shadow
        sharpen
        shave
        shear
        sigmoidal_contrast
        size
        sketch
        solarize
        splice
        spread
        strip
        swirl
        thumbnail
        tint
        transparent
        transpose
        transverse
        trim
        unsharp
        vignette
        wave
      ].freeze
    end
  end
end
