"""Tests for relay packet audit tool."""
import hashlib
import json
import subprocess
import tempfile


BINARY = "/app/target/release/relay-audit"
REPORT_PATH = "/app/output/report.json"
JOURNAL_PATH = "/app/data/journal.json"
CONFIG_PATH = "/app/config/relay.toml"


def compute_sha256(path):
    """Compute SHA-256 of a file."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


JOURNAL_SHA256 = None
CONFIG_SHA256 = None


def _init_hashes():
    global JOURNAL_SHA256, CONFIG_SHA256
    if JOURNAL_SHA256 is None:
        JOURNAL_SHA256 = compute_sha256(JOURNAL_PATH)
        CONFIG_SHA256 = compute_sha256(CONFIG_PATH)


_init_hashes()


def compute_hash(data, stage_id):
    """Independent hash computation matching the relay tool."""
    h = (stage_id * 0x9E3779B9) & 0xFFFFFFFF
    for b in data:
        h = ((h * 31) + b) & 0xFFFFFFFF
    return h


def compute_stage_checksum(data, stage_id, seed):
    """Independent stage checksum computation."""
    base = compute_hash(data, stage_id)
    return base ^ seed


def load_report():
    """Load the report generated by test.sh."""
    with open(REPORT_PATH) as f:
        return json.load(f)


class TestBinaryCompiles:
    """Verify that the project builds successfully."""

    def test_binary_compiles(self):
        """Cargo build --release must succeed."""
        result = subprocess.run(
            ["cargo", "build", "--release"],
            cwd="/app",
            capture_output=True,
            text=True,
        )
        assert result.returncode == 0, f"Build failed: {result.stderr}"


class TestDataIntegrity:
    """Verify input files are not modified."""

    def test_journal_unmodified(self):
        """Input journal.json must not be tampered with."""
        assert compute_sha256(JOURNAL_PATH) == JOURNAL_SHA256

    def test_config_unmodified(self):
        """Base config relay.toml must not be tampered with."""
        assert compute_sha256(CONFIG_PATH) == CONFIG_SHA256


class TestSummary:
    """Tests for aggregate summary correctness."""

    def test_total_packets(self):
        """Report must contain exactly 15 packets."""
        report = load_report()
        assert report["summary"]["total_packets"] == 15

    def test_all_reconciled_pass(self):
        """All 15 packets must pass reconciliation."""
        report = load_report()
        assert report["summary"]["reconciled_pass"] == 15

    def test_none_reconciled_fail(self):
        """Zero packets must fail reconciliation."""
        report = load_report()
        assert report["summary"]["reconciled_fail"] == 0

    def test_avg_drift_zero(self):
        """Average drift must be 0.0 when all packets are correct."""
        report = load_report()
        assert report["summary"]["avg_drift"] == "0.000000"

    def test_max_drift_zero(self):
        """Maximum drift must be 0.0."""
        report = load_report()
        assert report["summary"]["max_drift"] == "0.000000"

    def test_stages_active(self):
        """All 4 stages must be active."""
        report = load_report()
        assert report["summary"]["stages_active"] == 4

    def test_total_entries_replayed(self):
        """All 94 journal entries must be replayed (no truncation)."""
        report = load_report()
        assert report["summary"]["total_entries_replayed"] == 94

    def test_packets_truncated(self):
        """No packets should be truncated by replay window."""
        report = load_report()
        assert report["summary"]["packets_truncated"] == 0


class TestPerPacketReconciliation:
    """Verify each packet individually passes reconciliation."""

    def test_all_packets_reconciled_true(self):
        """Every packet must have reconciled = true."""
        report = load_report()
        for pkt in report["packets"]:
            assert pkt["reconciled"] is True, (
                f"{pkt['packet_id']}: reconciled={pkt['reconciled']}, "
                f"drift={pkt['drift_score']}"
            )

    def test_all_packets_zero_drift(self):
        """Every packet must have drift_score = 0.000000."""
        report = load_report()
        for pkt in report["packets"]:
            assert pkt["drift_score"] == "0.000000", (
                f"{pkt['packet_id']}: drift={pkt['drift_score']}"
            )

    def test_expected_equals_actual(self):
        """Expected and actual checksums must match for all packets."""
        report = load_report()
        for pkt in report["packets"]:
            assert pkt["expected_checksum"] == pkt["actual_checksum"], (
                f"{pkt['packet_id']}: expected={pkt['expected_checksum']} "
                f"actual={pkt['actual_checksum']}"
            )


class TestPacketEntries:
    """Verify correct entry counts per packet."""

    def test_pkt_001_entries(self):
        """pkt_001 has 6 journal entries, all must be replayed."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_001")
        assert pkt["entry_count"] == 6

    def test_pkt_002_entries(self):
        """pkt_002 has 10 entries (needs window >= 10)."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_002")
        assert pkt["entry_count"] == 10

    def test_pkt_004_entries(self):
        """pkt_004 has 12 entries (needs window >= 12)."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_004")
        assert pkt["entry_count"] == 12

    def test_pkt_008_entries(self):
        """pkt_008 has 11 entries (needs window >= 11)."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_008")
        assert pkt["entry_count"] == 11

    def test_pkt_011_entries(self):
        """pkt_011 has 9 entries (needs window >= 9)."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_011")
        assert pkt["entry_count"] == 9


class TestPayloadSizes:
    """Verify payload sizes are correct (no spurious truncation)."""

    def test_pkt_001_size(self):
        """pkt_001: 6 entries * 8 bytes = 48 bytes."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_001")
        assert pkt["payload_size"] == 48

    def test_pkt_004_size(self):
        """pkt_004: 12 entries * 6 bytes = 72 bytes."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_004")
        assert pkt["payload_size"] == 72

    def test_pkt_007_size(self):
        """pkt_007: 7 entries * 9 bytes = 63 bytes."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_007")
        assert pkt["payload_size"] == 63

    def test_pkt_012_size(self):
        """pkt_012: 6 entries * 12 bytes = 72 bytes (no off-by-one)."""
        report = load_report()
        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_012")
        assert pkt["payload_size"] == 72


class TestReportSchema:
    """Tests for JSON report structure."""

    def test_packets_array_exists(self):
        """Report must have a packets array."""
        report = load_report()
        assert "packets" in report
        assert isinstance(report["packets"], list)
        assert len(report["packets"]) == 15

    def test_summary_exists(self):
        """Report must have a summary object."""
        report = load_report()
        assert "summary" in report

    def test_packet_fields(self):
        """Each packet entry must have required fields."""
        report = load_report()
        required = {
            "packet_id", "stage_id", "expected_checksum",
            "actual_checksum", "drift_score", "reconciled",
            "payload_size", "entry_count",
        }
        for pkt in report["packets"]:
            missing = required - set(pkt.keys())
            assert not missing, f"{pkt.get('packet_id')}: missing {missing}"

    def test_checksum_hex_format(self):
        """Checksums must be formatted as 0xXXXXXXXX."""
        report = load_report()
        for pkt in report["packets"]:
            assert pkt["expected_checksum"].startswith("0x")
            assert len(pkt["expected_checksum"]) == 10
            assert pkt["actual_checksum"].startswith("0x")
            assert len(pkt["actual_checksum"]) == 10

    def test_sort_order(self):
        """Packets must be sorted by stage_id then packet_id."""
        report = load_report()
        packets = report["packets"]
        for i in range(len(packets) - 1):
            a, b = packets[i], packets[i + 1]
            if a["stage_id"] == b["stage_id"]:
                assert a["packet_id"] <= b["packet_id"], (
                    f"Sort violated: {a['packet_id']} > {b['packet_id']}"
                )
            else:
                assert a["stage_id"] < b["stage_id"]


class TestAntiCheat:
    """Anti-cheating tests with independently computed values."""

    def test_independent_checksum_pkt_001(self):
        """Independently verify checksum for pkt_001 (simple, in-order)."""
        report = load_report()
        with open(JOURNAL_PATH) as f:
            journal = json.load(f)

        # Get pkt_001 entries sorted by sequence_num
        pkt_entries = sorted(
            [e for e in journal["entries"] if e["packet_id"] == "pkt_001"],
            key=lambda e: e["sequence_num"],
        )

        # Accumulate state
        seed = 0x5678
        state = b""
        accumulated = seed
        for entry in pkt_entries:
            payload = bytes.fromhex(entry["payload"])
            entry_hash = compute_hash(payload, entry["stage_id"])
            accumulated = accumulated ^ entry_hash
            state += payload

        # Stage checksum
        stage_cs = compute_stage_checksum(state, 1, seed)
        expected = stage_cs ^ accumulated

        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_001")
        assert pkt["expected_checksum"] == f"0x{expected:08X}", (
            f"pkt_001: expected 0x{expected:08X}, got {pkt['expected_checksum']}"
        )

    def test_independent_checksum_pkt_004(self):
        """Independently verify pkt_004 (12 entries, needs full window)."""
        report = load_report()
        with open(JOURNAL_PATH) as f:
            journal = json.load(f)

        pkt_entries = sorted(
            [e for e in journal["entries"] if e["packet_id"] == "pkt_004"],
            key=lambda e: e["sequence_num"],
        )
        assert len(pkt_entries) == 12

        seed = 0x5678
        state = b""
        accumulated = seed
        for entry in pkt_entries:
            payload = bytes.fromhex(entry["payload"])
            entry_hash = compute_hash(payload, entry["stage_id"])
            accumulated = accumulated ^ entry_hash
            state += payload

        stage_cs = compute_stage_checksum(state, 2, seed)
        expected = stage_cs ^ accumulated

        pkt = next(p for p in report["packets"] if p["packet_id"] == "pkt_004")
        assert pkt["expected_checksum"] == f"0x{expected:08X}"

    def test_novel_single_packet(self):
        """Run tool with a novel single-packet journal."""
        payload = "AABBCCDD"
        novel = {
            "entries": [{
                "packet_id": "novel_001",
                "stage_id": 1,
                "sequence_num": 1,
                "timestamp": 100,
                "payload": payload,
                "checksum": 0,
                "padding_bytes": 0,
            }]
        }
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        ) as f:
            json.dump(novel, f)
            tmp = f.name

        subprocess.run(
            [BINARY, "--config", CONFIG_PATH, "--journal", tmp,
             "--output", "/app/output/novel1.json"],
            capture_output=True,
        )
        with open("/app/output/novel1.json") as f:
            result = json.load(f)

        assert result["summary"]["total_packets"] == 1
        assert result["summary"]["reconciled_pass"] == 1
        assert result["packets"][0]["reconciled"] is True
        assert result["packets"][0]["drift_score"] == "0.000000"

    def test_novel_multi_entry_packet(self):
        """Run tool with a packet that has 3 journal entries."""
        novel = {
            "entries": [
                {
                    "packet_id": "multi_001",
                    "stage_id": 2,
                    "sequence_num": 10,
                    "timestamp": 200,
                    "payload": "0102030405060708",
                    "checksum": 0,
                    "padding_bytes": 0,
                },
                {
                    "packet_id": "multi_001",
                    "stage_id": 2,
                    "sequence_num": 11,
                    "timestamp": 210,
                    "payload": "090A0B0C0D0E0F10",
                    "checksum": 0,
                    "padding_bytes": 0,
                },
                {
                    "packet_id": "multi_001",
                    "stage_id": 2,
                    "sequence_num": 12,
                    "timestamp": 220,
                    "payload": "1112131415161718",
                    "checksum": 0,
                    "padding_bytes": 0,
                },
            ]
        }
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        ) as f:
            json.dump(novel, f)
            tmp = f.name

        subprocess.run(
            [BINARY, "--config", CONFIG_PATH, "--journal", tmp,
             "--output", "/app/output/novel2.json"],
            capture_output=True,
        )
        with open("/app/output/novel2.json") as f:
            result = json.load(f)

        assert result["summary"]["reconciled_pass"] == 1
        assert result["packets"][0]["entry_count"] == 3
        assert result["packets"][0]["payload_size"] == 24
        assert result["packets"][0]["drift_score"] == "0.000000"

    def test_novel_ordering_matters(self):
        """Verify that sequence_num ordering produces correct result."""
        # Two entries with swapped timestamps but sequential sequence_nums
        novel = {
            "entries": [
                {
                    "packet_id": "order_001",
                    "stage_id": 3,
                    "sequence_num": 1,
                    "timestamp": 500,
                    "payload": "AABB",
                    "checksum": 0,
                    "padding_bytes": 0,
                },
                {
                    "packet_id": "order_001",
                    "stage_id": 3,
                    "sequence_num": 2,
                    "timestamp": 400,
                    "payload": "CCDD",
                    "checksum": 0,
                    "padding_bytes": 0,
                },
            ]
        }
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False
        ) as f:
            json.dump(novel, f)
            tmp = f.name

        subprocess.run(
            [BINARY, "--config", CONFIG_PATH, "--journal", tmp,
             "--output", "/app/output/novel3.json"],
            capture_output=True,
        )
        with open("/app/output/novel3.json") as f:
            result = json.load(f)

        # Must pass - correct ordering should give zero drift
        assert result["packets"][0]["reconciled"] is True
        assert result["packets"][0]["drift_score"] == "0.000000"

        # Verify the correct payload order (seq 1 then seq 2)
        # State should be AABB + CCDD = AABBCCDD
        seed = 0x5678
        p1 = bytes.fromhex("AABB")
        p2 = bytes.fromhex("CCDD")
        state = p1 + p2
        h1 = compute_hash(p1, 3)
        h2 = compute_hash(p2, 3)
        acc = seed ^ h1 ^ h2
        stage_cs = compute_stage_checksum(state, 3, seed)
        expected = stage_cs ^ acc
        assert result["packets"][0]["expected_checksum"] == f"0x{expected:08X}"


class TestDeterminism:
    """Tests for deterministic output."""

    def test_rerun_identical(self):
        """Running the tool twice produces identical output."""
        subprocess.run(
            [BINARY, "--config", CONFIG_PATH, "--journal", JOURNAL_PATH,
             "--output", REPORT_PATH],
            capture_output=True,
        )
        with open(REPORT_PATH) as f:
            first = f.read()
        subprocess.run(
            [BINARY, "--config", CONFIG_PATH, "--journal", JOURNAL_PATH,
             "--output", REPORT_PATH],
            capture_output=True,
        )
        with open(REPORT_PATH) as f:
            second = f.read()
        assert first == second
